### PR TITLE
Generate Giphy player like Facebook

### PR DESCRIPTION
**Pull request by lelinhtinh**
## Demo

https://jsfiddle.net/baivong/a4z0hz63/embedded/result,html,js/

### CODE REVIEW

**Comment by SethClydesdale** [comment]
That's a brilliant idea ! 👍

I tested it and it works perfectly. 😍 The only thing that I'd recommend changing is the following part, because it's version specific. ( `.post-entry` is a punbb only class )

``` javascript
var $giphyImg = $('.post-entry img[src*=".giphy.com/media/"][src$="giphy.gif"]');
```

Something like this should work perfectly cross-version : 

``` javascript
var $giphyImg = $('.postbody, .post-entry').find('img[src*=".giphy.com/media/"][src$="giphy.gif"]');
```

I think it'd be great to distribute this side-by-side with the SCEditor button. Is it alright with you if I include your plugin in my upcoming tutorial ? You'll be credited of course. Let me know 😄

**Comment by baivong** [comment]
Of course. I'm glad you appreciate it.

**Comment by lelinhtinh** [comment]
If so I should remove [`gifactif.key`](https://github.com/baivong/gifactif/blob/8e3f907fdb0f1484892165d6497807591c2bc5e9/gifactif-player.js#L67) or keep it?

**Comment by SethClydesdale** [comment]
@baivong Thanks, and great work ! ^^ Since this will most likely be used alongside the button plugin, it should be fine, because if the user ever changes their API key it'll be changed in your plugin as well. :wink:

**Comment by lelinhtinh** [comment]
I do not understand the meaning `side-by-side`, but you are free to use it in your way. :laughing:

**Comment by SethClydesdale** [comment]
"side-by-side" pretty much means two things that are close together -- similar to the word "alongside". What I meant is I'll share both codes in the same topic. I'll do the same in the repository too, once I add instructions to the readme. ^^

Thanks again for your contribution. 😄

**Pull request merged**
